spring:
  profiles:
    active: cloud
---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://lichunhui.xin:8761/eureka/
---
spring:
  profiles: dev
  application: 
    name : compute-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/